"""Build the release artifacts via PyInstaller.

The Windows path produces four artifacts under ``dist/``:

  - ``Trailbox.exe``      — windowed PyQt6 GUI (no console window).
  - ``Trailbox-mcp.exe``  — console MCP stdio server. With env var
                            ``TRAILBOX_HUB_URL`` it routes the 7 tools to a
                            remote Hub; without, it reads local ``output/``.
  - ``Trailbox-hub.exe``  — standalone Hub web server (fastapi/uvicorn).
                            Single-file alternative to the Docker image for
                            LAN deployments where a Linux container is overkill.
  - ``trailbox-bridge.exe`` — PyInstaller sidecar that the Tauri desktop app
                              spawns for capture / Hub API calls.
  - ``trailbox-desktop.exe`` — Rust + React Tauri shell. Produced by
                               ``npm run tauri:build`` which build.py invokes
                               on Windows (Node + Rust toolchain required).
                               Inno Setup renames this to ``Trailbox.exe`` at
                               install time.

Plus, if Inno Setup is installed, ``Trailbox-Setup.exe`` (installer wrapper).

The macOS path produces THREE Mach-O binaries (no ``.exe``):

  - ``Trailbox-mcp``      — same MCP stdio server, Mach-O build.
  - ``Trailbox-hub``      — same Hub web server, Mach-O build.
  - ``trailbox-bridge``   — Tauri sidecar (Mach-O). The Tauri-built ``.app``
                            spawns it for capture; you produce the ``.app``
                            itself separately via ``npm run tauri:build`` in
                            ``desktop-tauri/``. Per CLAUDE.md the PyQt6 GUI
                            stays Windows-only, so there's no Mac GUI build.

Each macOS binary gets an ad-hoc codesign pass
(``codesign --force --sign - --options runtime``). Notarization is a future
CI concern — see docs/mac-ios-capture-plan.md §A3.

GUI uses ``--windowed`` to suppress a console window; MCP & Hub are
``--console`` because both need stdin/stdout (stdio transport / log output).

Run from the venv:
  Windows:  ``.\\.venv\\Scripts\\python.exe build.py``
  macOS  :  ``./.venv/bin/python build.py``
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import imageio_ffmpeg


_IS_DARWIN = sys.platform == "darwin"
_IS_WIN = sys.platform == "win32"

# Icon source per platform. The macOS .icns was generated by `tauri icon`
# alongside the desktop bundle's icon set so the PyInstaller binaries' Finder
# previews match the Tauri app.
_ICON = (
    "desktop-tauri/src-tauri/icons/icon.icns" if _IS_DARWIN
    else "assets/trailbox.ico"
)

# Suffix for the PyInstaller `--name` outputs. On macOS Mach-O binaries
# carry no extension by convention; on Windows everything is `.exe`.
_EXE = ".exe" if _IS_WIN else ""

# GUI uses --onedir so cold-start doesn't pay the 120MB extraction-to-%TEMP%
# tax that --onefile imposes on every launch. Installer (.iss) and the
# _run_pyinstaller exit-path resolution below were updated together.
# Windows-only: per CLAUDE.md the PyQt6 GUI stays Windows-only; mac users go
# through the Tauri shell. This constant is unused on macOS builds.
_GUI_FLAGS = [
    "--onedir",
    "--windowed",
    "--name", "Trailbox",
    "--icon", "assets/trailbox.ico",
    # Bundle the icon as data so Qt can load it at runtime for the window/taskbar.
    "--add-data", "assets/trailbox.ico" + os.pathsep + "assets",
    "--collect-data", "soundcard",
    "--collect-data", "windows_capture",
    "--collect-data", "imageio_ffmpeg",
    "--collect-submodules", "comtypes",
    "--collect-submodules", "pynput",
    # ffmpeg binary added by _run_pyinstaller for both builds.
    # Android tooling (adb + scrcpy) added by _android_binary_flags() if the
    # files are present. Missing tools/android/ trees just skip the bundling —
    # the resulting .exe will then fail at runtime when the user picks the
    # Android radio, with a friendlier message from core.adb.
]

# MCP build pulls in only what the stdio server needs.
# ``mcp.cli`` requires optional ``typer``; skip it via targeted submodule pulls.
# ffmpeg is bundled so the ``get_frame_at`` tool can extract video frames
# from screen.mp4 — that single feature is why this exe isn't 13 MB anymore.
# httpx is needed when TRAILBOX_HUB_URL is set (HubBackend HTTP calls).
_MCP_FLAGS = [
    "--onefile",
    "--console",
    "--name", "Trailbox-mcp",
    "--icon", _ICON,  # file icon only (no Qt window)
    "--collect-data", "imageio_ffmpeg",
    "--collect-submodules", "mcp_server",
    "--collect-submodules", "mcp.server",
    "--collect-submodules", "mcp.shared",
    "--collect-submodules", "mcp.types",
    "--hidden-import", "httpx",
]

# Hub build is the FastAPI/uvicorn server bundled standalone. No Qt, no mcp,
# no capture stack. ffmpeg is bundled for the /api/sessions/{id}/frame route.
_HUB_FLAGS = [
    "--onefile",
    "--console",
    "--name", "Trailbox-hub",
    "--icon", _ICON,
    "--collect-data", "imageio_ffmpeg",
    "--collect-submodules", "hub_server",
    "--collect-submodules", "uvicorn",
    "--collect-submodules", "fastapi",
    "--hidden-import", "python_multipart",
    # Phase 0.7.0: Jinja2 templates + CSS/JS for the web UI. Bundled at
    # hub_server/{templates,static}/ inside the .exe; hub_server.app /
    # hub_server.routes.web resolve them via sys._MEIPASS at runtime.
    "--add-data", "hub_server/templates" + os.pathsep + "hub_server/templates",
    "--add-data", "hub_server/static" + os.pathsep + "hub_server/static",
    # Phase 0.5.0+ auth dependencies — PyInstaller doesn't always pick these
    # up via static analysis because they're imported lazily.
    "--hidden-import", "argon2",
    "--hidden-import", "argon2.exceptions",
    "--hidden-import", "argon2_cffi_bindings",
    "--hidden-import", "itsdangerous",
    "--hidden-import", "itsdangerous.url_safe",
    "--collect-submodules", "jinja2",
]


# Bridge build for Tauri desktop app. Bundles bridge.py + bridge_record.py +
# all core modules needed for recording, window enumeration, and Hub API calls.
# Windows-only collects (soundcard / windows-capture / comtypes) are appended
# conditionally below — on macOS they're unavailable and PyInstaller would
# refuse to bundle them.
_BRIDGE_FLAGS = [
    "--onefile",
    "--console",
    "--name", "trailbox-bridge",
    "--icon", _ICON,
    "--collect-data", "imageio_ffmpeg",
    "--collect-submodules", "pynput",
    "--hidden-import", "httpx",
    # Include the bridge modules as data so the entry point can import them
    "--add-data", "desktop-tauri/bridge.py" + os.pathsep + ".",
    "--add-data", "desktop-tauri/bridge_record.py" + os.pathsep + ".",
]
if _IS_WIN:
    _BRIDGE_FLAGS += [
        "--collect-data", "soundcard",
        "--collect-data", "windows_capture",
        "--collect-submodules", "comtypes",
    ]
else:
    # macOS iOS-capture stack — pyobjc + pymobiledevice3 are imported lazily
    # inside the recorder threads (see core/ios_*.py / screen_recorder.py),
    # so PyInstaller's static analysis can miss them. Pull them in explicitly.
    _BRIDGE_FLAGS += [
        "--collect-submodules", "AVFoundation",
        "--collect-submodules", "CoreMediaIO",
        "--collect-submodules", "Foundation",
        "--collect-submodules", "pymobiledevice3",
    ]


def _android_binary_flags(repo_root: Path) -> tuple[list[str], list[Path]]:
    """Return ``--add-binary`` args for the bundled Android tools, plus the
    list of bundled paths (for logging).

    Both subtrees are optional; if neither is present we return ([], []) and
    the GUI build still works for monitor/window capture. Files are flattened
    into ``bin/`` inside the bundle so ``core.adb`` resolves them with a
    simple ``_MEIPASS/bin/<name>`` lookup.

    Drop the upstream zip contents under:
      tools/android/platform-tools/   (adb.exe + AdbWinApi.dll + AdbWinUsbApi.dll)
      tools/android/scrcpy/           (scrcpy.exe + scrcpy-server.jar + DLLs)
    """
    base = repo_root / "tools" / "android"
    flags: list[str] = []
    bundled: list[Path] = []
    if not base.is_dir():
        return flags, bundled

    # Flatten platform-tools/* and scrcpy/* into a single _MEIPASS/bin/ dir.
    # Anything that isn't a regular file (e.g. nested resource dirs scrcpy
    # ships) is skipped — scrcpy only needs the loose top-level files.
    for sub in ("platform-tools", "scrcpy"):
        d = base / sub
        if not d.is_dir():
            continue
        for entry in d.iterdir():
            if entry.is_file():
                flags += ["--add-binary", f"{entry};bin"]
                bundled.append(entry)
    return flags, bundled


def _find_iscc() -> Path | None:
    """Locate the Inno Setup compiler. Returns None if not installed."""
    # winget installs Inno Setup per-user under AppData\Local\Programs.
    candidates = [
        Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Inno Setup 6" / "ISCC.exe",
        Path("C:/Program Files (x86)/Inno Setup 6/ISCC.exe"),
        Path("C:/Program Files/Inno Setup 6/ISCC.exe"),
    ]
    for p in candidates:
        if p.is_file():
            return p
    found = shutil.which("ISCC.exe") or shutil.which("iscc")
    return Path(found) if found else None


def _build_tauri_windows(repo_root: Path) -> Path | None:
    """Build the Tauri desktop shell on Windows and stage it in ``dist/``.

    The Inno Setup script (`installer/Trailbox-installer.iss`) ships
    ``dist/trailbox-desktop.exe`` as the user-facing GUI launcher (Inno
    renames it to ``Trailbox.exe`` at install time). That binary is produced
    by ``npm run tauri:build`` in ``desktop-tauri/`` — a Rust + React build
    that lives outside PyInstaller's reach. We invoke it here so a single
    ``python build.py`` run yields every artifact the installer needs;
    historically this was a manual step and forgetting it left Inno Setup
    failing with "Source file ... trailbox-desktop.exe does not exist."

    If ``npm`` isn't on PATH we skip with a clear message rather than
    failing the whole build — that lets PyInstaller-only iterations work
    on machines without Node / Rust installed.
    """
    npm = shutil.which("npm")
    desktop_dir = repo_root / "desktop-tauri"
    if npm is None or not (desktop_dir / "package.json").is_file():
        print("\n=== skipping Tauri shell build (npm or desktop-tauri/ missing) ===")
        return None
    print(f"\n=== building Tauri shell ({desktop_dir.name}) ===")
    print(f"$ {npm} run tauri:build  (cwd={desktop_dir})")
    subprocess.run([npm, "run", "tauri:build"], cwd=desktop_dir, check=True)
    src = desktop_dir / "src-tauri" / "target" / "release" / f"trailbox-desktop{_EXE}"
    if not src.is_file():
        raise RuntimeError(f"Tauri build did not produce {src}")
    dst = repo_root / "dist" / src.name
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    print(f"staged {dst.name} → {dst}")
    return dst


def _build_installer(repo_root: Path) -> Path | None:
    """Compile the Inno Setup installer if ISCC.exe is available.

    Requires Trailbox.exe / Trailbox-mcp.exe / Trailbox-hub.exe /
    trailbox-desktop.exe in dist/ (the last one staged by
    :func:`_build_tauri_windows`).
    """
    iscc = _find_iscc()
    iss = repo_root / "installer" / "Trailbox-installer.iss"
    if iscc is None or not iss.is_file():
        print("\n=== skipping installer (ISCC.exe or .iss not found) ===")
        return None

    print(f"\n=== building Trailbox-Setup.exe ({iss.name}) ===")
    print(f"$ {iscc} {iss}")
    subprocess.run([str(iscc), str(iss)], check=True, cwd=iss.parent)
    out = repo_root / "dist" / "Trailbox-Setup.exe"
    if not out.is_file():
        raise RuntimeError(f"Inno Setup did not produce {out}")
    return out


def _run_pyinstaller(
    entry: str, flags: list[str], ffmpeg_exe: Path, repo_root: Path
) -> Path:
    cmd = [sys.executable, "-m", "PyInstaller", *flags]
    # ffmpeg goes into every build — GUI uses it for recording, MCP/Hub for
    # frame extraction, bridge for both. PyInstaller's --add-binary separator
    # follows the platform PATH separator (';' on win, ':' on mac/linux).
    cmd += ["--add-binary", f"{ffmpeg_exe}{os.pathsep}imageio_ffmpeg/binaries"]
    cmd += [entry]
    name = flags[flags.index("--name") + 1]
    print(f"\n=== building {name}{_EXE} ({entry}) ===")
    print("$ " + " ".join(c if os.pathsep not in c else f'"{c}"' for c in cmd))
    subprocess.run(cmd, check=True, cwd=repo_root)
    # --onedir puts the launcher at dist/<name>/<name>{ext} alongside _internal/;
    # --onefile leaves it at dist/<name>{ext} directly. ext is .exe on win, ""
    # on mac.
    if "--onedir" in flags:
        out = repo_root / "dist" / name / f"{name}{_EXE}"
    else:
        out = repo_root / "dist" / f"{name}{_EXE}"
    if not out.exists():
        raise RuntimeError(f"PyInstaller did not produce {out}")
    return out


def _codesign_adhoc(binary: Path) -> None:
    """Apply a bare ad-hoc (`-`) signature to ``binary``.

    Per docs/mac-ios-capture-plan.md §A3 decision table, v1 ships with ad-hoc
    signatures; users bypass Gatekeeper on first launch via right-click → Open.
    Apple Developer signing + ``xcrun notarytool`` is a future CI concern.

    Hardened runtime (``--options runtime``) is deliberately NOT enabled here:
    PyInstaller ``--onefile`` builds extract a nested ``Python.framework`` at
    launch which is signed by python.org with their Team ID. Hardened runtime
    refuses to dlopen libraries from a different Team ID than the host
    process, so the bare ad-hoc binary dies at startup with
    "code signature ... not valid for use in process: mapping process and
    mapped file (non-platform) have different Team IDs". When we move to
    notarization we'll re-introduce ``--options runtime`` together with an
    entitlements plist granting ``com.apple.security.cs.disable-library-
    validation`` (or switch to ``--onedir`` so the framework is shipped
    pre-signed under our identity).

    ``--force`` re-signs if a previous signature exists (PyInstaller
    occasionally leaves a stub from its internal re-signing pass).
    """
    if shutil.which("codesign") is None:
        print(f"  (codesign not found — skipping {binary.name})")
        return
    cmd = ["codesign", "--force", "--sign", "-", str(binary)]
    print(f"  codesign --sign - {binary.name}")
    subprocess.run(cmd, check=True)


def _find_tauri_app(repo_root: Path) -> Path | None:
    """Locate the most recently built Trailbox.app under desktop-tauri.

    Tauri 2 drops the bundle at target/{release,debug}/bundle/macos/
    Trailbox.app. Prefer release; fall back to debug so this step still
    works against a `tauri dev`-built bundle if someone wants to iterate.
    """
    base = repo_root / "desktop-tauri" / "src-tauri" / "target"
    for profile in ("release", "debug"):
        cand = base / profile / "bundle" / "macos" / "Trailbox.app"
        if cand.is_dir():
            return cand
    return None


def _plist_set(plist: Path, key: str, value: str) -> None:
    """Idempotently set ``Info.plist[key] = value`` via PlistBuddy.

    PlistBuddy's ``Add`` errors if the key exists; ``Set`` errors if it
    doesn't. Delete-then-Add covers both states without per-call branching.
    """
    pb = "/usr/libexec/PlistBuddy"
    subprocess.run(
        [pb, "-c", f"Delete :{key}", str(plist)],
        stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, check=False,
    )
    subprocess.run(
        [pb, "-c", f"Add :{key} string {value}", str(plist)],
        check=True,
    )


# User-facing strings in Korean to match the rest of the desktop UI.
# Surfaced in the macOS permission prompts when the user first triggers
# a capture; without these the prompt shows only the bundle id.
_USAGE_DESCRIPTIONS: dict[str, str] = {
    # CMIO devices (a tethered iPhone surfaced via AVFoundation) use the
    # camera permission model — same prompt as built-in cameras.
    "NSCameraUsageDescription":
        "Trailbox는 연결된 iPhone을 캡처 디바이스로 사용합니다.",
    # ScreenCaptureKit (Mac desktop/window capture) — not in this branch's
    # scope yet but cheap to declare now so the eventual capture-on-mac
    # path doesn't need a separate Info.plist pass.
    "NSScreenCaptureUsageDescription":
        "Trailbox는 화면 캡처로 세션을 기록합니다.",
    # System audio capture (SCK 13+).
    "NSMicrophoneUsageDescription":
        "Trailbox는 시스템 사운드를 함께 기록합니다.",
}


def _iter_macho_binaries(root: Path):
    """Yield every Mach-O file under ``root``. Used for the codesign sweep.

    We rely on ``file -b`` to identify Mach-O headers because that's the
    same heuristic Apple's codesign uses internally and it covers nested
    frameworks / dylibs / executables uniformly.
    """
    for path in root.rglob("*"):
        if not path.is_file() or path.is_symlink():
            continue
        try:
            out = subprocess.check_output(
                ["file", "-b", str(path)], stderr=subprocess.DEVNULL
            ).decode("utf-8", errors="ignore")
        except subprocess.CalledProcessError:
            continue
        if "Mach-O" in out:
            yield path


def _codesign_app_deep(app: Path) -> None:
    """Sign every nested Mach-O bottom-up, then the bundle root.

    ``codesign --deep`` exists but Apple's guidance is to sign nested
    components individually for predictable behaviour with the hardened
    runtime / notarization. We do the same here so the v1 ad-hoc step
    matches the eventual notarization flow.
    """
    binaries = sorted(_iter_macho_binaries(app), key=lambda p: -len(p.parts))
    for b in binaries:
        subprocess.run(
            ["codesign", "--force", "--sign", "-", str(b)],
            check=True,
        )
    # Final pass: re-sign the bundle root so its CodeResources reflect the
    # nested signatures we just wrote.
    subprocess.run(
        ["codesign", "--force", "--sign", "-", str(app)],
        check=True,
    )


def _bundle_darwin(repo_root: Path) -> int:
    """Post-process ``Trailbox.app`` produced by ``npm run tauri:build``.

    Steps (in order):
      1. Locate the .app under ``desktop-tauri/src-tauri/target/.../bundle/macos/``.
      2. Copy ``dist/trailbox-bridge`` into ``Contents/MacOS/`` so the Tauri
         launcher's ``current_exe().parent()`` resolves the sidecar at runtime
         (matches commands.rs ``BRIDGE_NAME`` resolution).
      3. Inject the Korean usage-description strings into ``Info.plist``.
      4. Codesign every nested Mach-O ad-hoc, then re-sign the bundle root.

    Idempotent: re-running is a no-op for the copy/Info.plist (overwrites)
    and just re-signs binaries with the same ad-hoc identity.
    """
    app = _find_tauri_app(repo_root)
    if app is None:
        print(
            "Trailbox.app not found — run `cd desktop-tauri && npm run "
            "tauri:build` first.",
            file=sys.stderr,
        )
        return 2

    bridge_src = repo_root / "dist" / "trailbox-bridge"
    if not bridge_src.is_file():
        print(
            f"{bridge_src} missing — run `python build.py` first to produce "
            "the sidecar.",
            file=sys.stderr,
        )
        return 2

    print(f"app: {app}")
    bridge_dst = app / "Contents" / "MacOS" / "trailbox-bridge"
    print(f"copying sidecar → {bridge_dst}")
    shutil.copy2(bridge_src, bridge_dst)
    bridge_dst.chmod(0o755)

    plist = app / "Contents" / "Info.plist"
    print(f"injecting usage descriptions → {plist}")
    for key, value in _USAGE_DESCRIPTIONS.items():
        _plist_set(plist, key, value)

    print("codesign sweep (ad-hoc, no hardened runtime)")
    _codesign_app_deep(app)

    print("\n=== verify ===")
    subprocess.run(
        ["codesign", "--verify", "--verbose=2", str(app)], check=False
    )
    print(f"\n=== done ===\n  {app}")
    return 0


def _build_darwin(repo_root: Path, ffmpeg_exe: Path) -> int:
    """macOS pipeline: MCP + Hub + bridge (no GUI), ad-hoc codesigned.

    The PyQt6 GUI is not built on mac — the Tauri shell in ``desktop-tauri/``
    is the supported mac frontend (run ``npm run tauri:build`` separately to
    produce ``Trailbox.app``). For the resulting ``.app`` to actually find
    the sidecar, ``trailbox-bridge`` needs to land next to the Tauri launcher
    inside ``Trailbox.app/Contents/MacOS/`` — that copy step is left to the
    Tauri build / a follow-up bundle script. (Notarization is also a
    follow-up CI concern.)
    """
    mcp_exe = _run_pyinstaller("mcp_entry.py", _MCP_FLAGS, ffmpeg_exe, repo_root)
    hub_exe = _run_pyinstaller("hub_entry.py", _HUB_FLAGS, ffmpeg_exe, repo_root)
    bridge_exe = _run_pyinstaller(
        "desktop-tauri/bridge_entry.py", _BRIDGE_FLAGS, ffmpeg_exe, repo_root
    )

    outputs = [mcp_exe, hub_exe, bridge_exe]
    print("\n=== ad-hoc codesigning ===")
    for path in outputs:
        _codesign_adhoc(path)

    print("\n=== done ===")
    for path in outputs:
        size_mb = path.stat().st_size / 1024 / 1024
        print(f"  {path}  ({size_mb:.1f} MB)")
    print(
        "\nNext: cd desktop-tauri && npm run tauri:build  "
        "# produces Trailbox.app + .dmg\n"
        "Then: python build.py mac-bundle  "
        "# copies the sidecar into the .app + Info.plist usage descriptions "
        "+ codesign sweep"
    )
    return 0


def _build_windows(repo_root: Path, ffmpeg_exe: Path) -> int:
    """Windows pipeline: GUI + MCP + Hub + bridge, plus the Inno Setup wrapper."""
    android_flags, android_bundled = _android_binary_flags(repo_root)
    if android_bundled:
        print(f"bundling {len(android_bundled)} Android tool file(s) under bin/")
    else:
        print(
            "tools/android/ not populated - Android capture will be disabled in this "
            "build (see README for the platform-tools / scrcpy download steps)"
        )

    gui_exe = _run_pyinstaller(
        "main.py", _GUI_FLAGS + android_flags, ffmpeg_exe, repo_root
    )
    mcp_exe = _run_pyinstaller("mcp_entry.py", _MCP_FLAGS, ffmpeg_exe, repo_root)
    hub_exe = _run_pyinstaller("hub_entry.py", _HUB_FLAGS, ffmpeg_exe, repo_root)
    bridge_exe = _run_pyinstaller(
        "desktop-tauri/bridge_entry.py", _BRIDGE_FLAGS, ffmpeg_exe, repo_root
    )

    # Tauri shell — Rust + React build that the installer wraps as Trailbox.exe.
    # Failing here aborts the run rather than half-baking the installer step.
    tauri_exe = _build_tauri_windows(repo_root)
    installer_exe = _build_installer(repo_root)

    print("\n=== done ===")
    outputs = [gui_exe, mcp_exe, hub_exe, bridge_exe]
    if tauri_exe is not None:
        outputs.append(tauri_exe)
    if installer_exe is not None:
        outputs.append(installer_exe)
    for path in outputs:
        # For --onedir GUI, report the whole bundle size (launcher + _internal/),
        # not just the small launcher .exe — the bundle is what installer ships.
        if path.parent.name == path.stem:
            total = sum(f.stat().st_size for f in path.parent.rglob("*") if f.is_file())
        else:
            total = path.stat().st_size
        size_mb = total / 1024 / 1024
        print(f"  {path}  ({size_mb:.1f} MB)")
    return 0


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parent

    # Subcommand dispatch — currently only mac-bundle. Everything else
    # falls into the platform-default build pipeline (Windows: full +
    # installer; macOS: 3 PyInstaller binaries). Kept manual instead of
    # argparse to stay dependency-free.
    args = list(argv) if argv is not None else sys.argv[1:]
    if args == ["mac-bundle"]:
        if not _IS_DARWIN:
            print("mac-bundle only runs on macOS", file=sys.stderr)
            return 2
        return _bundle_darwin(repo_root)
    if args:
        print(f"unknown args: {args!r}", file=sys.stderr)
        print("usage: python build.py [mac-bundle]", file=sys.stderr)
        return 2

    ffmpeg_exe = Path(imageio_ffmpeg.get_ffmpeg_exe())
    print(f"platform: {sys.platform}")
    print(f"ffmpeg: {ffmpeg_exe}")

    # Wipe everything so consecutive builds don't share stale work/PYZ caches.
    for p in [repo_root / "build", repo_root / "dist"]:
        if p.exists():
            print(f"cleaning {p}")
            shutil.rmtree(p, ignore_errors=True)
    for spec in repo_root.glob("*.spec"):
        spec.unlink()

    if _IS_DARWIN:
        return _build_darwin(repo_root, ffmpeg_exe)
    if _IS_WIN:
        return _build_windows(repo_root, ffmpeg_exe)
    print(f"unsupported platform: {sys.platform}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
